name: TRC Weddings
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15165437012910843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010100'
    - '#34352d'
    - '#c3ad24'
    - '#686957'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
